"""Add grid_charging_disabled_for_demand field

Revision ID: 1bc1a0544dad
Revises: 5d33e3c502f5
Create Date: 2025-12-06 17:37:33.785838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc1a0544dad'
down_revision = '5d33e3c502f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grid_charging_disabled_for_demand', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('grid_charging_disabled_for_demand')

    # ### end Alembic commands ###
