"""Add solar_curtailment_enabled field to user table

Revision ID: 37d78bc60237
Revises: 888d4f9ca20c
Create Date: 2025-11-23 20:36:20.977539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d78bc60237'
down_revision = '888d4f9ca20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solar_curtailment_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('solar_curtailment_enabled')

    # ### end Alembic commands ###
