"""Add last_tariff_hash column for deduplication

Revision ID: 5d33e3c502f5
Revises: ccabed9ec07b
Create Date: 2025-12-02 17:35:17.129222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d33e3c502f5'
down_revision = 'ccabed9ec07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_tariff_hash', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_tariff_hash')

    # ### end Alembic commands ###
