"""Add fleet_api_redirect_uri column

Revision ID: ab08488206e2
Revises: 6f59916b99d5
Create Date: 2025-12-10 18:02:27.326119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab08488206e2'
down_revision = '6f59916b99d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fleet_api_redirect_uri', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fleet_api_redirect_uri')

    # ### end Alembic commands ###
