"""Add cached export rule to user model

Revision ID: ccabed9ec07b
Revises: d62ca471b7bd
Create Date: 2025-12-02 06:54:27.078383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccabed9ec07b'
down_revision = 'd62ca471b7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_export_rule', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_export_rule_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_export_rule_updated')
        batch_op.drop_column('current_export_rule')

    # ### end Alembic commands ###
