"""Add amber_site_id to User model

Revision ID: d62ca471b7bd
Revises: 7ba8a45bfd47
Create Date: 2025-11-30 17:54:38.698666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62ca471b7bd'
down_revision = '7ba8a45bfd47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amber_site_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('amber_site_id')

    # ### end Alembic commands ###
