"""Add Flow Power electricity provider configuration

Revision ID: f8a3c7e92d14
Revises: 60416c1edc02
Create Date: 2025-12-13 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a3c7e92d14'
down_revision = '60416c1edc02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('electricity_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('flow_power_state', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('flow_power_price_source', sa.String(length=20), nullable=True))

    # Set default value for electricity_provider to 'amber' for existing users
    op.execute("UPDATE user SET electricity_provider = 'amber' WHERE electricity_provider IS NULL")
    op.execute("UPDATE user SET flow_power_price_source = 'amber' WHERE flow_power_price_source IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('flow_power_price_source')
        batch_op.drop_column('flow_power_state')
        batch_op.drop_column('electricity_provider')

    # ### end Alembic commands ###
